### PR TITLE
Fix broken initialization of `Firebase::Admin::Messaging::MulticastMessage`

### PR DESCRIPTION
**Pull request by ohbarye**
Hello. 

I found a broken initialization of `Firebase::Admin::Messaging::MulticastMessage`. The class does not have `topic` method nor `condition` method.

I brought those descriptions from https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages.

### CODE REVIEW

**Comment by skatkov** [comment]
Thanks for submitting this PR. Can I ask you to add a test to this Pull Request as well?

**Comment by ohbarye** [comment]
I added a quite minimum test to cover this fix. How about [2519fa7](https://github.com/cheddar-me/firebase-admin-sdk-ruby/pull/16/commits/2519fa7611d6c1a02271d99d276346dfa65843de)?

**Review by skatkov — APPROVED** [review]

**Comment by skatkov** [comment]
@ohbarye thanks for your contribution, this small test will do :)

**Comment by skatkov** [comment]
I just issued a new release with this fix (0.3.1)

**Comment by ohbarye** [comment]
Thanks for your review and quick release!

**Pull request merged**
